services:
  lsv-api:
    image: ghcr.io/quijadajose/lsv-backend:latest
    restart: unless-stopped
    depends_on:
      - lsv-db
    env_file:
      - ./.env
    environment:
      - DB_HOST=lsv-db
    networks:
      - lsv_network

  lsv-frontend:
    image: ghcr.io/quijadajose/lsv-frontend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - lsv_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  lsv-db:
    image: postgres:18.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    env_file:
      - ./.env
    volumes:
      - db_data_psql:/var/lib/postgresql/data
      - ./lsv-backend/init-db:/docker-entrypoint-initdb.d
    networks:
      - lsv_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  lsv_network:
    driver: bridge

volumes:
  db_data_psql:
