services:
  lsv-api:
    command: npm run start:prod
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
    expose:
      - "3000"

  lsv-frontend:
    expose:
      - "80"


volumes:
  db_data_psql:
  valkey_data:
