services:
  lsv-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/src/app
    command: npm run start:debug
    depends_on:
      - lsv-db
    ports:
      - 3000:3000
      - 9229:9229

  lsv-db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  lsv-test:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/src/app
      - /src/app/node_modules
    command: pnpm run test:e2e
    depends_on:
      - lsv-db
    profiles:
      - test

volumes:
  db_data:
